### ISSUE TITLE
Operator "==" not working when the attributed class is in the same assembly as call site

### ISSUE THREAD

**Issue by IvanMacek** [Fody/Equals#10]
Hi, it seems to me that the Fody generated operator "==" is not working when the attributed class with [Equals] is in the same assembly as call site.

I've done a runnable example which demonstrates the issue: https://github.com/IvanMacek/FodyEqualsFailExample

Call to the Equals method works as expected. 
When the class is implemented in the another assembly operator "==" works as expected.

Thank you for your time!

Cheers,
Ivan

**Comment by SimonCropp** [comment]
@rjasica still working on this? @IvanMacek any chance you want to try for a PR?

**Comment by IvanMacek** [comment]
@SimonCropp sorry I don't have an active project using Fody so I don't have time to play with this :(

**Comment by mikhailshilkov** [comment]
Do you guys have an example of a workaround?

**Comment by rjasica** [comment]
Sorry for inconvenience, but it is not easy to implement this feature.

Workaround: Move type to new/other assembly.

**Comment by SimonCropp** [comment]
@rjasica so what do we do with this one? Close as not possible to fix?

**Comment by MarkusAmshove** [comment]
Hi guys,

I just stumbled over this (after not being able to figure out what the problem was :) ).

Is there any chance this might be supported in the future?

The following workaround is working btw:
```
[Equals(DoNotAddEqualityOperators =true)]
public class Point
{
    ...
    
    public static operator==(Point left, Point right) => left.Equals(right);
    public static operator!=(Point left, Point right) => !left.Equals(right);
}
```

**Comment by mutzl** [comment]
What a bummer!
This is really, really dangerous.
Even analyzing the decompiled class containing the [Equals] attribute will not point to the issue, because the issue is hidden in the usage of the operator by this unwanted cast to (object).

So I suggest, making the default of DoNotAddEqualityOperators = true;
(Which is of course a breaking change.)

Nevertheless: there needs to be a highlyvisible warning on the first page about this unpredictable behaviour. 
(I personally lost a day due to this.)

**Comment by orc886** [comment]
How can the developer not fixed it yet?

**Comment by SimonCropp** [comment]
@orc886 a PR would be appreciated

**Comment by SimonCropp** [comment]
@rjasica thoughts on @mutzl suggestions

**Comment by orc886** [comment]
Sorry, I might missed what PR means

**Comment by SimonCropp** [comment]
@orc886 as in if it is valueable to you it would be great if you could fix it

**Comment by SimonCropp** [comment]
let me know if anyone gets a PR done

**Comment by BrunoJuchli** [comment]
Note: I'll implement the PR for the proposal, given I can convince the team to allocate time for it. Which depends on your feedback to the proposal.

Proposal
--
(Breaking Change)
Do not weave == & != operators.
User has to manually add `==` and `!=` operators, like @MarkusAmshove showed:

    [Equals(DoNotAddEqualityOperators =true)]
    public class Point
    {
        public static operator==(Point left, Point right) => left.Equals(right);
        public static operator!=(Point left, Point right) => !left.Equals(right);
    }

Optionally: For maximum backwards compatibility, add a settings switch to FodyWeavers.xml which allows to weave == & != operators by default (i.E. ignore the problem).

Reasoning
--

No Solution Available
---

The compiler translates the following two statements to the same IL:

    f1 == f2 // should use the woven implementation
    ReferenceEquals(f1, f2) // should retain reference equality semantics

Thus, it's not viable for Equals.Fody to rewrite the "right" IL instructions (`ceq`, `beq`, maybe others...) to use `left.Equals(right)` instead.
If we'd do this, we'd break explicit calls of `ReferenceEquals`.
That's not a sholution, that's just shifting the problem around.

Hence, the best we can do is to prevent the problem from happening.


Severity
---

We've recently hit this issue (again, I believe).
I think there's a significant risk that a programmer & tests won't notice the different behavior when a type is moved to the same assembly as the usage.
While tests might pass in the same instance of an object actual implementation might use multiple equivalent instances. The test would thus not fail if reference equality was applied.

Thus I believe it's critical enough to warrant a breaking change.

Question
--

Apart from whether the proposal is generally acceptable, I would like to propose to remove weaving of `==` and `!=` operators alltogether.
Providing it as an opt-in is nice, but it's more code to maintain, more tests to write. And this issue can never been resolved, so it's always going to be buggy.

For transparency and safety reason's I'd vote for removing weaving of the operators entirely and update the documentation accordingly.

**Comment by SimonCropp** [comment]
> I would like to propose to remove weaving of == and != operators alltogether.

i am happy with this. and happy with your proposal overall :)

**Comment by ltrzesniewski** [comment]
Shouldn't the operators continue to be weaved on value types?

**Comment by BrunoJuchli** [comment]
@ltrzesniewski 
Good point, I'll have to investigate. I  don't know how equality works for structs.

**Comment by tom-englert** [comment]
For the operators to work in the same assembly, they have to be present in the source at compile time - but Fody adds them after compile!

You should write it like this, an let Fody replace the implementation afterwards:
```c#
public class Point
{
    public static operator==(Point left, Point right) => throw new NotImplementedException();
    public static operator!=(Point left, Point right) => throw new NotImplementedException();
}```

**Comment by BrunoJuchli** [comment]
@tom-englert 
IMHO the difference between copy-pasting:

    public static operator==(Point left, Point right) => throw new NotImplementedException();
    public static operator!=(Point left, Point right) => throw new NotImplementedException();

and

    public static operator==(Point left, Point right) => left.Equals(right);
    public static operator!=(Point left, Point right) => !left.Equals(right);

is quite small, that's why I suggested Equals.Fody should skip implementing the operator alltogether.

Performance wise there exists a slight difference as with using `left.Equals(right)` the `Equals(object)` overload will be called instead of `Equals(point)`.
Is this performance benefit worth the additional complexity in Equals.Fody?

**Comment by BrunoJuchli** [comment]
@tom-englert 
I've been thinking about this a bit more.
Just replacing the operators seems dangerous, too: In the (un-common and strange) case of actually implementing the operators with a *different* logic, them being silently replaced would be a big surprise. So it seems it would be nice to be able to mark operators for replacement. Of course one could argue that this is being done by `[Equals]` on the class, but IMHO that's not exactly great because of the vertical distance between the class declaration and the operators (it's not obvious that there's a connection).
What'd be an option is something like:

    public static operator==(Point left, Point right) => Equals.Weave();
    public static operator!=(Point left, Point right) => Equals.Weave();

where `Equals` is a class in the same assembly as `EqualsAttribute` and has an implementation like:

    throw new Exception("This method call should have been replaced by Equals.Fody. Weaving seems to be defective".)

I'm not sure how easy it is to parse this call, reliably, from the IL. And what we should do with with types that have the operators but don't match.

The simplest I can think of is just supporting exactly one scenario, which is, you copy paste the lines as above, and if you haven't, the build will fail. You get an all-or-nothing kind of deal.
Of course this could be extended to opt-out of operator weaving (as now).

One important question is how bad it really is to weave `Equals`/`GetHashCode` methods but not to overload the `==` and `!=` operators.

**Comment by BrunoJuchli** [comment]
@ltrzesniewski
> Shouldn't the operators continue to be weaved on value types?

    public struct Struct1
    {
        public bool Foo()
        {
            return this == new Struct1();
        }
    }

doesn't compile because apparently `struct`s don't have `==` and `!=` by default.
Changing the code to:

    [Equals]
    public struct Struct1
    {
        public static bool operator ==(Struct1 c1, Struct1 c2) => true;
        public static bool operator !=(Struct1 c1, Struct1 c2) => true;
    }

The build spits out a Fody error (see below).
I'm using Fody 5.1.1 and Equals.Fody 2.0.1.

Conclusion: equivalency operators on structs are not supported by Equals.Fody, my proposed change doesn't change anything for structs.

>    Error: Fody: An unhandled exception occurred:
Exception:
Member 'System.Boolean op_Equality(Equals.Fody.Repro10.Struct1,Equals.Fody.Repro10.Struct1)' is declared in another module and needs to be imported
Type:
System.ArgumentException
StackTrace:
   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider) in C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:line 2228
   at Mono.Cecil.Cil.CodeReader.PatchRawCode(ByteBuffer buffer, Int32 code_size, CodeWriter writer) in C:\Code\Fody\cecil\Mono.Cecil.Cil\CodeReader.cs:line 585
   at Mono.Cecil.Cil.CodeReader.PatchRawFatMethod(ByteBuffer buffer, CodeWriter writer, Int32& code_size, MetadataToken& local_var_token) in C:\Code\Fody\cecil\Mono.Cecil.Cil\CodeReader.cs:line 519
   at Mono.Cecil.Cil.CodeReader.PatchRawMethodBody(MethodDefinition method, CodeWriter writer, Int32& code_size, MetadataToken& local_var_token) in C:\Code\Fody\cecil\Mono.Cecil.Cil\CodeReader.cs:line 491
   at Mono.Cecil.Cil.CodeWriter.WriteUnresolvedMethodBody(MethodDefinition method) in C:\Code\Fody\cecil\Mono.Cecil.Cil\CodeWriter.cs:line 73
   at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method) in C:\Code\Fody\cecil\Mono.Cecil.Cil\CodeWriter.cs:line 49
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method) in C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:line 1643
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type) in C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:line 1635
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type) in C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:line 1433
   at Mono.Cecil.MetadataBuilder.AddTypes() in C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:line 1405
   at Mono.Cecil.MetadataBuilder.BuildTypes() in C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:line 1259
   at Mono.Cecil.MetadataBuilder.BuildModule() in C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:line 1029
   at Mono.Cecil.MetadataBuilder.BuildMetadata() in C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:line 999
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _) in C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:line 137
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read) in C:\Code\Fody\cecil\Mono.Cecil\ModuleDefinition.cs:line 930
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata) in C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:line 136
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters) in C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:line 115
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters) in C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:line 77
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters) in C:\Code\Fody\cecil\Mono.Cecil\ModuleDefinition.cs:line 1119
   at InnerWeaver.WriteModule() in C:\projects\fody\FodyIsolated\ModuleWriter.cs:line 19
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 111
Source:
Mono.Cecil
TargetSite:
Mono.Cecil.MetadataToken LookupToken(Mono.Cecil.IMetadataTokenProvider)

**Comment by MarkusAmshove** [comment]
I like the idea of `Equals.Weave`, as a `NotImplementedException` would be yelled at from static analysis tools  :-)

**Comment by BrunoJuchli** [comment]
> I like the idea of `Equals.Weave`, as a `NotImplementedException` would be yelled at from static analysis tools :-)

But who is still using the IL based ones, like FxCop? Nowadays we mostly use Roslyn based code analyzers and those don't inspect the contents of `Equals.Weave` at all. Not sure if FxCop did, anyway (Equals being a third party assembly).

**Comment by MarkusAmshove** [comment]
Exactly, I mean using `Equals.Weave()` instead of the former proposal:

```
public static operator==(Point left, Point right) => throw new NotImplementedException();
public static operator!=(Point left, Point right) => throw new NotImplementedException();
```

because the latter would raise issues in our static analysis

**Comment by BrunoJuchli** [comment]
@SimonCropp 
I've run into a bit of a pickle.
Even if I leave the `ModuleWeaver.Execute()` method completely empty, weaving the assembly replaces a method reference with an invalid one:

![image](https://user-images.githubusercontent.com/2090172/60729612-71a86f80-9f43-11e9-988e-88ba0b1553a0.png)

![image](https://user-images.githubusercontent.com/2090172/60729639-81c04f00-9f43-11e9-9588-1326261a6d4f.png)

So after weaving "nothing", the IL points to a type `[ReferencedDependency]Operator` instead of `[Equals]Operator`. Have you seen something like this before? Currently I believe it might be a Cecil bug..

**Comment by ltrzesniewski** [comment]
This is most likely caused by [this line](https://github.com/Fody/Equals/blob/40355c688a6f3777e29a10a266f5e33fda644442/Equals.Fody/ModuleWeaver.cs#L135) which tells Fody to remove the reference to the `Equals` assembly. It supposes the weaver removed all references to its library during weaving. If you leave code which references `Equals`, it will be broken.

**Comment by BrunoJuchli** [comment]
@ltrzesniewski 
Thanks! So i guess this is a problem other add-ins are affected by, too?
Whenever you place a reference somewhere unexpected and it doesn't get picked up/replaced by the AddIn you've got faulty IL. Or are other add-ins searching the whole IL for references? Is there a sensible way to do that?

I'm tempted to just ignore the issue as "by design", although it would be very preferable to report to the user that he's doing something wrong instead of having him experience enigmatic errors...

**Comment by ltrzesniewski** [comment]
I don't see this as a problem but as something that's by design: the weaver is supposed to clean up after itself. It's usually not a problem for most weavers, but they almost all assume the user is using the weaver library as intended. Many weaver libraries only supply attributes, so you can end up with invalid metadata, which won't prevent your code from running.
I tried to implement something more robust in InlineIL, as it heavily relies on the user calling the library's methods. I think I got it mostly right but it involved a nontrivial amount of code and I don't think it's worth the effort for most weavers. I thought about extracting this code and submitting it as a PR to Fody, but that would probably end up breaking addins that neglect to cleanup properly without it causing serious consequences, so I didn't do that in the end.

**Comment by BrunoJuchli** [comment]
It'd be nice if someone could review #96. Thanks.

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.
